### ISSUE TITLE
Never finding streams

### ISSUE THREAD

**Issue by ghostmansd** [sch3m4/libntoh#11]
During libntoh testing, it was shown that libntoh never actually finds a stream, but always creates a new one. Here is an example source file.
https://gist.github.com/ghostmansd/5cb5b6f41fe72e554696

**Comment by hoxnox** [comment]
Hi. The same for me (gentoo, gcc-4.9.2). Removing _HIDDEN helps.

**Comment by luongnv89** [comment]
Hi,
Same for me: gcc (Ubuntu 15.04)
Removing _HIDDEN attribute from the functions in sfhash.c fixes it.

**Comment by sch3m4** [comment]
So, removed _HIDDEN attribute. Thank you all!
