### ISSUE TITLE
code understand

### ISSUE THREAD

**Issue by jiamo** [sch3m4/libntoh#13]
In tcpreassembly.c `handle_closing_connection func` ,  why at the end call the `send_peer_segments` again while at the beginning or this func already call it?

**Comment by sch3m4** [comment]
It was a workaround for some synchronization issues... The code has suffered several modifications about synchronization, now it's pretty stable however that portion of code has not been reviewed... So I need to verify if the second call  never sends segments to the user (as it should be in an ideal world) to remove the call (bogus call). Feel free to test some scenarios (with out-of-order segment, "urgent" flagged segments, etc.) and submit a patch.

Thank you!
