### ISSUE TITLE
PythonLibs not found when running CMake

### ISSUE THREAD

**Issue by Talkopel** [sch3m4/libntoh#14]
Don't know if this just happened to me, but in any case the fix is to add the python-dev to the needed packages for compilation. 

Also - libpthread-dev should be installed with this name libpthread-stubs0-dev

I would update the instructions :)
Thank you!

**Comment by sch3m4** [comment]
the python wrapper has been deleted because it is not ready to be functional, it was only a technical approach, I'll keep your comment in mind to the future. However, thank your for opening this issue!
